from __future__ import annotations

from .bayesian_personalized_ranking_loss import PairwiseBPR
from .cross_entropy_loss import MaskedCrossEntropyLoss
from .knowledge_distillation_loss import DistilKLLoss
from .margin_based_distillation_loss import DistilMarginMSE
from .pairwise_nll_loss import InBatchPairwiseNLL
from .pairwise_nll_loss import PairwiseNLL
from .ranking_consistency_loss import Divergence
from .ranking_distillation_loss import ListMLE
from .ranking_distillation_loss import ListNet
